<div class="wordpress-sample">
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Sample Site</th>
            <th>Sample</th>
            <th>Build by</th>
            <th>Build on</th>
            <th>Action</th>
        </tr>
        <?php foreach($this->sampleSites as $index => $sampleSite): ?>
        <tr>
            <td><?php echo ++$index ?> </td>
            <td>
                <?php echo $sampleSite->name ?>
                <a target="_blank" href="http://<?php echo $sampleSite->name ?>" title="Go to site">[site]</a>
                <a target="_blank" href="http://<?php echo $sampleSite->name ?>/wp-admin" title="Go to site">[admin]</a>
            </td>
            <td><?php echo $sampleSite->buildfrom ?></td>
            <td><?php echo $sampleSite->buildby ?></td>
            <td><?php echo $sampleSite->buildon ?></td>
            <td>
                <!-- <a href="/api/create-wordpress/sample-id/1/domain/dev.photoshop.com" >Make site</a> -->
                <a href="#" class="linkMakeSite  icon-shopping-cart" olddomain="<?php echo $sampleSite->name ?>" title="Make site"></a>
                <a target="_blank" href="http://<?php echo $sampleSite->name ?>" class="icon-globe" title="Go to site"></a>
                <a href="/api/duplicate-wordpress/olddomain/<?php echo $sampleSite->name ?>" class="icon-leaf" title="Duplicate to site"></a>
                <a href="/api/delete-wordpress/domain/<?php echo $sampleSite->name ?>/type/sample" class="icon-remove" title="Delete this site"></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<div class="modal hide fade" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Site information</h3>
    </div>
    <div class="modal-body">
        <span>Please input your domain</span>
        <p>Your domain <input type="text" class="input-large" name="domain" id="txtDomain"/></p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" id="btnCloseModal">Close</a>
        <a href="#" class="btn btn-primary" id="btnMakeSite">Make Site</a>
    </div>
</div>
<script type="text/javascript">
    var olddomain;
    $('.linkMakeSite').click(function(){
        olddomain = $(this).attr('olddomain');
        $('#myModal').modal('show');
    })
    $('#btnCloseModal').click(function(){
        $('#myModal').modal('hide');
        sampleSiteId = null;
    });
    $('#btnMakeSite').click(function(){
        var url = "/api/create-wordpress/olddomain/"+ olddomain + "/domain/" + $('#txtDomain').val();
        alert(url);
        $.ajax({
            url: url,
            type: 'JSON',
            success: function(data){
                if(data.result == true){
                    alert('Success');
                    $('#myModal').modal('hide');
                }else{
                    alert('Fail');
                    $('#myModal').modal('hide');
                }
            }
        })
    })
</script>