<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headTitle(); ?>
  <?php $this->headScript()->appendFile('/js/jquery-1.9.1.min.js') ?>
  <?php $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.min.css') ?>
  <?php $this->headScript()->appendFile('/bootstrap/js/bootstrap.min.js') ?>
   <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headMeta() ?>
</head>
<body>
    <div class="container">
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>