<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headTitle(); ?>
  <?php $this->headScript()->appendFile('/js/jquery-1.9.1.min.js') ?>
  <?php $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.min.css') ?>
  <?php $this->headScript()->appendFile('/bootstrap/js/bootstrap.min.js') ?>
  <?php $this->headLink()->appendStylesheet('/css/style.css') ?>
   <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headMeta() ?>
</head>
<body>

    <div class="container-fluid">
        <div class="banner"></div>
        <div class="row-fluid">
            <div class="span2">
                 <h4>Wordpress</h4>
                 <ul>
                    <li><a href="/site/sample">Samples</a></li>
                    <li><a href="/site/site">Sites</a></li>
                    <li><a href="/trash/sample/">Trash Samples </a></li>
                    <li><a href="/trash/site">Trash Sites</a></li>
                 </ul>
            </div>
            <div class="span10">
            <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
</body>
</html>